services:
  nginx:
    build:
      context: ..
      dockerfile: docker/nginx/dockerfile
      target: production
    ports:
      - ${NGINX_PORT}:80
      - ${NGINX_SSL_PORT}:443
    environment:
      - APP_DOMAIN=${APP_DOMAIN}
      - NGINX_SSL_PORT=${NGINX_SSL_PORT}