services:
  mariadb:
    image: mariadb:11.4.2-noble
    restart: unless-stopped
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=1
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DOCKER_DB_PORT}:3306