services:
  app:
    restart: unless-stopped
    build:
      context: ..
      dockerfile: docker/app/dockerfile
      target: production
      args:
        - REQUIREMENTS=${REQUIREMENTS}
        - PHP_REQUIREMENTS=${PHP_REQUIREMENTS}
        - USERNAME=${USERNAME:-laravel}
    environment:
      - APP_ENV=${APP_ENV}
      - APP_DEBUG=${APP_DEBUG}
      - APP_URL=https://${APP_DOMAIN}
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}

  nginx:
    extends:
      file: compose.nginx.yml
      service: nginx
