name: boilerplates-laravel

services:
  app:
    extends:
      file: compose.yml
      service: app
    build:
      target: development
    environment:
      - DEBUG_INIT=${DEBUG_INIT:-false}
    volumes:
      - ../:/app
      - ${HOME}/.ssh:/home/${USERNAME}/.ssh

  nginx:
    extends:
      file: compose.nginx.yml
      service: nginx
    build:
      target: development
      args:
        - APP_DOMAIN=${APP_DOMAIN}
    volumes:
      - ./nginx/conf.d/:/etc/nginx/templates/
      # - ../:/app
