name: ${APP_NAME}

services:
  app:
    build:
      context: ..
      dockerfile: docker/app/dockerfile
      target: production
      args:
        - REQUIREMENTS=${REQUIREMENTS}
        - PHP_REQUIREMENTS=${PHP_REQUIREMENTS}
    environment:
      - DB_CONNECTION=${DB_CONNECTION}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD==${DB_PASSWORD}

  nginx:
    build:
      context: ..
      dockerfile: docker/nginx/dockerfile
      target: production
    ports:
      - ${NGINX_PORT}:80
      - ${NGINX_SSL_PORT}:443
    environment:
      - APP_DOMAIN=${APP_DOMAIN}
      - NGINX_SSL_PORT=${NGINX_SSL_PORT}