services:
  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      - MARIADB_RANDOM_ROOT_PASSWORD=1
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DOCKER_DB_PORT}:3306
    volumes:
      - storage_mariadb:/var/lib/mysql
    networks:
      - default

volumes:
  storage_mariadb:
